### ISSUE TITLE
Calling Moltin.Products.UpdateRelationships(moltinId, 'category', []) fails

### ISSUE THREAD

**Issue by aravindanve** [moltin/js-sdk#108]
Hi!

Calling `await Moltin.Products.UpdateRelationships(moltinId, 'category', [])` to clear all `Product <=> Category` relationships fails with the following error:

````JSON
{
    "message": {
        "errors": [
            {
                "status": 500,
                "title": "Internal Server Error",
                "detail": "There was an internal server error, you can report with your request id.",
                "request_id": "6c8b4050dc4c0eb2"
            }
        ]
    }
}
````

Although a `PUT` request directly placed to the endpoint works.

Take a look at the code here on `Line: 8`

https://github.com/moltin/js-sdk/blob/6ebcb9985221a3dfc11fdf2b4ed6bae963167594/src/utils/helpers.js#L4-L16

All other return statements return an `Array` whereas, this line returns a string. Which I suppose is again converted to JSON string with `JSON.stringify(body)` resulting in `"[]"` instead of `[]`

**Comment by ynnoj** [comment]
@aravindanve Are you able to share the full request payload built from the library?

**Comment by ynnoj** [comment]
If you're trying to remove all existing relationships, then `UpdateRelationships` would be the right method to use.

```js
Moltin.Products.UpdateRelationships(id, 'category')
```

I suspect the `500` you're seeing is because you're using `CreateRelationships` with an empty payload. Let me know if this helps 🙃

**Comment by aravindanve** [comment]
Hi @ynnoj 

Sorry, my mistake. I meant `Moltin.Products.UpdateRelationships(id, 'category')`. I've updated the issue.

**Comment by ynnoj** [comment]
@aravindanve Can you share the payload in the request body please?

**Comment by aravindanve** [comment]
I'm using it in the backend. I need to do a quick browser test to get the request payload from the sdk. Hold on.

**Comment by aravindanve** [comment]
@ynnoj here you go! (https://runkit.com/aravindanve/moltin1)

**Comment by ynnoj** [comment]
Looks like your hypothesis is correct! 😄

**Comment by aravindanve** [comment]
Hi @ynnoj, any idea on when this will be merged?

**Comment by ynnoj** [comment]
Hey @aravindanve. Will be merged and published this morning.

**Comment by ynnoj** [comment]
`2.6.2` just published with this fix 🎉

**Comment by aravindanve** [comment]
@ynnoj Perfect! Thank You!
