### ISSUE TITLE
Stock Management

### ISSUE THREAD

**Issue by aravindanve** [moltin/js-sdk#114]
How do I get Product Inventory, create or retrieve Stock Transactions using the sdk?

**Comment by ynnoj** [comment]
Hey @aravindanve, great question. The inventory service is still a work in progress on the API, hence why its yet to make it in to the SDK.

Once that lands and is integrated with products/catalogue, then it'll be a priority to get that it added.

**Comment by aravindanve** [comment]
@ynnoj alright. I have temporarily extended the sdk on my end. I look forward to the update!
