### ISSUE TITLE
422 HTTP error when POST /v2/customers

### ISSUE THREAD

**Issue by vohzd** [moltin/js-sdk#135]
https://docs.moltin.com/v2/?javascript#create-a-customer

I'm following the example above exactly, and receiving a `422 Unprocessable Entity` response. I can create products fine & I am using the `client_credentials` `grant_type`

I have tried Moltin `3.3.0` & `3.4.0`

**Comment by notrab** [comment]
Hi @vohzd 

Our API reference appears to showing an incorrect payload. I'll make sure this is updated within the API reference ASAP.

The payload should contain `type': 'customer'` 😄 

```js
var customer = {
    name: "Ron Swanson",
    email: "ron@swanson.com",
    password: "mysecretpassword",
    type: 'customer'
}

Moltin.Customers.Create(customer).then((response) => {
  // Do something
});
```

**Comment by vohzd** [comment]
Thanks for your swift response! I can confirm this has resolved the issue!
