### ISSUE TITLE
Console error: "Synchronous XMLHttpRequest is deprecated"

### ISSUE THREAD

**Issue by lindseydiloreto** [moltin/js-sdk#14]
Using this code:

    moltin.Authenticate(function() {
        var product = moltin.Product.Find({slug: 'test-product'});
    });

... produces this console error in Chrome:

> (moltin.js:126) Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by lindseydiloreto** [comment]
To be fair, it's a **warning**, not an error... I misspoke.

**Comment by abmohan** [comment]
@lindseydiloreto, pass a callback as the second argument to `moltin.Product.Find` if you'd like it to work asynchronously.
