### ISSUE TITLE
Loading node libraries in the browser  

### ISSUE THREAD

**Issue by astr0sl0th** [moltin/js-sdk#156]
Hi,

You are tying to load nodejs libraries in the browser and it is causing a few issues when I am trying to compile via webpack.

The library in question is local-storage this is not compatible with the browser and you should be using the built in browser local storage.

**Comment by notrab** [comment]
Hi @astr0sl0th 

Thanks for creating the issue. I'll be sure to look into this with @ynnoj to try and resolve your issue. I know we've both had similar issues recently and we're actively looking for ways to improve the SDK around `localStorage` usage.

One idea we had was to split the SDK into 2 different packages, for Node and the browser.

Another idea is to remove the storage functionality and require the user to implement their own storage around handling/remembering auth tokens and cart IDs.

I'd love to know your thoughts and as always, pull requests are welcome for any ideas you have to add to the SDK.

**Comment by notrab** [comment]
Hi @astr0sl0th 

Could you try and update your Webpack config to include the following...

```js
node: {
  fs: 'empty'
}
```

This should sort the issue. It's outlined in the README and completely slipped my mind.

**Comment by astr0sl0th** [comment]
ng-cli handles my webpack configuration so there still my be an issue. I
will check once back at my desk tomorrow.

**Comment by notrab** [comment]
Great. @craigtweedy have you recently used the `ng-cli` with `@moltin/sdk`? Interested to hear your experience too.

**Comment by astr0sl0th** [comment]
Worked okay since ng-cli 1.7.4 then updated to ng-cli 6.0.0 and it turns
out ng-cli has stricter rules with what it does and doesn’t allow.

I was in discussion with the angular team members Sander Elias and Clydin

Sander suggested I use this patch until the issue is sorted.

As a workaround I have added to my tsconfig

"paths": { "node-localstorage": ["noop.js"] }

noop.js contains:

export const noop = () => undefined;


This works but it’s rather hacky I think the real root of this problem lyes
with your storage untility.

I would suggest you prioritise support for your browser sdk as chances are
people using sever side access will have a database they use for other
parts of thier app logic so maybe strip  node-localstorage and let the
developer choose how he wants to store cart and auth tokens.

I would submit a pull request but I think this logic is better off decided
by you guys as I’m sure you have a some very experienced engineers 😉

**Comment by astr0sl0th** [comment]
Worked okay since ng-cli 1.7.4 then updated to ng-cli 6.0.0 and it turns
out ng-cli has stricter rules with what it does and doesn’t allow now.

I was in discussion with the angular team members Sander Elias and Clydin

Sander suggested I use this patch until the issue is sorted.

As a workaround I have added to my tsconfig

`"paths": { "node-localstorage": ["noop.js"] }`

noop.js contains:

`export const noop = () => undefined;`


This works but it’s rather hacky I think the real root of this problem lyes
with your storage untility.

I would suggest you prioritise support for your browser sdk as chances are
people using sever side access will have a database they use for other
parts of thier app logic so maybe strip  node-localstorage and let the
developer choose how he wants to store cart and auth tokens.

I would submit a pull request but I think this logic is better off decided
by you guys as I’m sure you have a some very experienced engineers 😉

**Comment by notrab** [comment]
Hey @astr0sl0th, let me know if you have any issues upgrading to `3.14.0`.
