### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by sethkrasnianski** [moltin/js-sdk#21]
Any reason why indentation is with 8 spaces instead of the conventional 2?

**Comment by sethkrasnianski** [comment]
@outrunthewolf

**Comment by outrunthewolf** [comment]
Well... Looking at this:
 - https://github.com/polarmobile/coffeescript-style-guide#tabs-or-spaces

It seems we should be adhering to the 2 space rule common with normal JS. However, i'm no front-end expert so I can only go with the general rules i've picked up.

Your thoughts?

**Comment by sethkrasnianski** [comment]
Hmm... It seems that the project is. Github is just formatting it with incorrect indentation. I'll look into it

**Comment by sethkrasnianski** [comment]
After a second look, it seems that vim was autocorrecting the indentation for me as best as it could. I think it was checked into get with incorrect indentation. I'll fix it up

**Comment by jHoldroyd** [comment]
I've just gone through and ensured we're using standard indentation on the src files, thanks for pointing this out.
