### ISSUE TITLE
Minify UNPKG Lib

### ISSUE THREAD

**Issue by DanielSokil** [moltin/js-sdk#218]
When adding `https://unpkg.com/@moltin/sdk@3.12.1/dist/moltin.js` script to a project, the `moltin.js` file does not seem to be minified, Are there any plans to minify that file?

**Comment by MartinKolarik** [comment]
You can use https://cdn.jsdelivr.net/npm/@moltin/sdk@3.12.1/dist/moltin.min.js for a minified version.

**Comment by DanielSokil** [comment]
@MartinKolarik Thanks for your help!

**Comment by DanielSokil** [comment]
I think `https://cdn.jsdelivr.net/npm/@moltin/sdk@3.12.1/dist/moltin.min.js` should be added to README.md
