### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by outrunthewolf** [moltin/js-sdk#24]
> Hi,
Is there any doc about the authenticate endpoint ?
By default there is no password field in the Customer Flow.
Also i don't understand how the authentification is handled as i don't see when the auth credentials I suppose customers/authenticate returns are stored.
Thanks

@machard Moved to issue rather than on the pr.

There are two types of authentication.

One, is using the access token endpoint to get an access token to enable you to make requests to the API. http://moltin.github.io/documentation/authenticate/

The second is customer authentication. This is not in general release as yet and you will not be able to use it until early january.

**Comment by camwes** [comment]
@outrunthewolf It says that this can be expected by January but I noticed that this [PR]( https://github.com/moltin/js-sdk/pull/23/) is still open? How would recommend proceeding?
