### ISSUE TITLE
Failed to compile with Angular 7

### ISSUE THREAD

**Issue by mamayadi** [moltin/js-sdk#246]
After importing the `@moltin/sdk` I failed to compile my project this is the error:

> ERROR in ./node_modules/graceful-fs/polyfills.js
> Module not found: Error: Can't resolve 'constants' in 'C:\...\moltin-api\node_modules\graceful-fs'
> ERROR in ./node_modules/graceful-fs/graceful-fs.js
> Module not found: Error: Can't resolve 'fs' in 'C:\...\moltin-api\node_modules\graceful-fs'
> ERROR in ./node_modules/node-localstorage/LocalStorage.js
> Module not found: Error: Can't resolve 'fs' in 'C:\...\moltin-api\node_modules\node-localstorage'
> ERROR in ./node_modules/node-localstorage/LocalStorage.js
> Module not found: Error: Can't resolve 'path' in 'C:\...\moltin-api\node_modules\node-localstorage'
> ERROR in ./node_modules/graceful-fs/legacy-streams.js
> Module not found: Error: Can't resolve 'stream' in 'C:\...\moltin-api\node_modules\graceful-fs'

This is my Dependencies version:

> "@angular/animations": "~7.1.0",
>     "@angular/common": "~7.1.0",
>     "@angular/compiler": "~7.1.0",
>     "@angular/core": "~7.1.0",
>     "@angular/forms": "~7.1.0",
>     "@angular/platform-browser": "~7.1.0",
>     "@angular/platform-browser-dynamic": "~7.1.0",
>     "@angular/router": "~7.1.0",
>     "@moltin/sdk": "^3.18.2",
>     "core-js": "^2.5.4",
>     "rxjs": "~6.3.3",
>     "tslib": "^1.9.0",
>     "zone.js": "~0.8.26"

After searching, I understand that I should make: `node: {fs:'empty'}` but I don't know where to insert this code.

Any suggestion, Thank you.

**Comment by mamayadi** [comment]
I solved by going to: 
> node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js
 and change: `node: false` to `node: {fs: 'empty'}`

Hope this help so one 😊

**Comment by premsmishra** [comment]
This worked for me, thank you @mamayadi :)
