### ISSUE TITLE
Inconsistent pagination with SDK when filtering products

### ISSUE THREAD

**Issue by nikolubbe** [moltin/js-sdk#249]
Hi :) 

I'm having some trouble with filtering and pagination. 

Whenever I do a product get call via the SDK [ i.e. `Moltin.Products.Filter(...).All` ] the resultset has a random amount of duplicate products in it.

Example: 
```javascript 
let _ = require('lodash')
const MoltinGateway = require("@moltin/sdk").gateway;

let gateway = {
    client_id: "8NNRJcFqSk7nkxrutpaNZpcKlBduaVHH8i9UV1WWXU",
};

async function getProductsWith() {
    let Moltin = MoltinGateway(gateway);
    let products = await Moltin.Products.Filter({eq: {"collection.id": '517fba26-5c17-4758-9f33-f4a1538a0233'}}).All().catch();
    while (products.data.length < products.meta.results.total) {
        let d = await Moltin.Products.Filter({eq: {"collection.id": '517fba26-5c17-4758-9f33-f4a1538a0233'}}).Offset(products.data.length).All().catch();
        products.data = products.data.concat(d.data)
    }
    return products.data;
}

for (let i = 0; i < 5; i++) {
    getProductsWith().then(function (response) {
        let deduped = _.uniqBy(response, "id");
        console.log("Unique items returned: ", deduped.length)
    });
}
```
Results in: 
```bash
$ node demo.js
Unique items returned:  515
Unique items returned:  515
Unique items returned:  529
Unique items returned:  515
Unique items returned:  553
```

I've tried Sorting with the filter but it's still not correct. Adding a `desc` sort seems to make it better (there's less variance between the returned lengths). Interestingly, with `.Sort("-sku")` it seems to be correct?

Thanks!

**Comment by notrab** [comment]
Hey @nikolubbe 

This may well be an issue with the API. Have you been able to replicate this making requests via cURL or [`moltin-request`](https://github.com/moltin/moltin-request)?

I'll look into this a bit more my side. Apologies for any trouble caused.

**Comment by nikolubbe** [comment]
I'll run some tests and let you know 👍

**Comment by nikolubbe** [comment]
Looks like it's probably an issue with the API as I was able to reproduce this with cURL: 
```bash 
$ for i in `seq 0 100 500`; do curl "https://api.moltin.com/v2/products?page\[limit\]=100&page\[offset\]={$i}&filter=eq(collection.id,517fba26-5c17-4758-9f33-f4a1538a0233)" \
-H 'Authorization: Bearer: XXXX' \
-H 'Content-Type: application/json' --compressed | jq '.data[].id' >> out.txt; done
```

Results: 
```bash
$ cat out.txt | wc -l
     553
```
```bash
$ sort out.txt | uniq -c | wc -l
     504
```

**Comment by ynnoj** [comment]
@nikolubbe 👋 We've identified the issue you've encountered as an API problem. In this instance I'm going to close this issue and we can track the resolution of the bug over on your original [forum thread](https://forum.moltin.com/t/inconsistent-pagination-with-sdk-when-filtering-products/1517/2).

Thanks!
