### ISSUE TITLE
Is Node SDK production ready?

### ISSUE THREAD

**Issue by larsha** [moltin/js-sdk#25]
Hi, I talked to customer support on moltin.com and I told them we're planning on using Moltin with Node. The response I got back was that the Node SDK might not be production ready yet? 

Any input on that response, is it safe to start use it or will we experience bugs? What I can see on this repository it seems it's ready for production? Or are there any known bugs?

Cheers,
Fredrik

**Comment by noname00000123** [comment]
@larsha Have you made an attempt? Am currently integrating with moltin, but have had difficulty making Authenticating.

Receiving this **error**
> XMLHttpRequest cannot load http://localhost:9091/sockjs-node/info?t= 1449187563637. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://0.0.0.0:8080' is therefore not allowed access.

Have found *a* solution and raised a seperate issue to track progress, see moltin/js-sdk#26

**Comment by larsha** [comment]
Hi @noname00000123, no, I heard from Moltin Slack channel that they still have some work to Node SDK and minor refactoring to be done, so we proceed building our own wrapper around the API instead for now.

**Comment by outrunthewolf** [comment]
We're working on a new version of the SDK now.
