### ISSUE TITLE
Fetching order with Implicit + Token

### ISSUE THREAD

**Issue by shendriksza** [moltin/js-sdk#255]
The following call fails with a permission (403) response:
`const getOrder = (token, id) => Moltin.Orders.With('items').Get(id, token)`
Which is silly, because I can query all orders which includes the order I need:
`const getAllOrders = (token) => Moltin.Orders.With('items').All(token)`

Does Get() and All() expect different tokens? Shouldn't I be able to query a single order given it already associated with a certain customer? Is there a workaround if this is not the case?

**Comment by ynnoj** [comment]
@shendriksza 👋 thanks for opening an issue!

I've managed to replicate this issue outside of this library by making direct requests to the API. I've raised this issue internally and will work to have it triaged and fixed.

Will report back once resolved. In the meantime please work around this accordingly. Sorry for the inconvenience.

**Comment by shendriksza** [comment]
Any update on when this will be addressed?
