### ISSUE TITLE
Need a custom `data` argument when checking out a cart

### ISSUE THREAD

**Issue by monkeybroth** [moltin/js-sdk#258]
The current checkout mechanism accepts 'customer', 'billing', and 'shipping'. I have a Flow that extends orders that is a required field.

So when checking out the cart, I get thrown an error that the Flow value is missing. But there isn't a way to pass in this custom data.

The workaround I currently use is to change the field into an optional field, then Update the order with that custom Flow value.

**Comment by field123** [comment]
Hi 👋 @monkeybroth 

This issue is rather old I'm closing it for now. If it's still an issue in the most recent version of the SDK could you please reopen and provide a small reproducible example or some code snippets for more context and we will take a look.
