### ISSUE TITLE
Updating cart says product not found

### ISSUE THREAD

**Issue by itswadesh** [moltin/js-sdk#306]
Here is my put request to cart
--------------------------------------
`https://api.moltin.com/v2/carts/ce8fdd3b4d384f3089c4396c91216fe5/items/49d70992-e052-4a91-a986-e87111244206`

request payload 
----------------------
`data: {type: "cart_item", id: "49d70992-e052-4a91-a986-e87111244206", quantity: 1}`

The response says product not found. Where as the product was added using Cart post request

**Comment by samblacklock** [comment]
@itswadesh 

Hey Swadesh, for clarity can you confirm that you are seeing this issue using the SDK?

If you `GET` this cart can you see the items in it?

**Comment by itswadesh** [comment]
Hello Sam,

Thanks for responding. 

Yes I am using javascript sdk with vuejs

Yes I am getting back the cart items and trying to modify that item quantiry.

Here is the repo https://github.com/itswadesh/misiki-books

If you add to cart -> go to cart -> press the -ve button to decrease the cart quantity, you get the error message

**Comment by samblacklock** [comment]
Hey @itswadesh it looks like you are using the `product` ID on the `PUT` request. To update the cart item, you should use the `cart_item` ID instead

I will close this issue as it is not directly an issue with the JS SDK, however if you have any more issues please feel free to get in touch with our support team directly here: https://support.moltin.com/hc/en-us/requests/new

Thanks!

**Comment by itswadesh** [comment]
@samblacklock Hey Sam,

Am I doing it wrong? I wish to update the quantity of a product in cart

I can increase the quantity using  `addToBag(item.product_id,1)`

How to decrease the quantity? because `addToBag(item.product_id,-1)` negative quantity throws an error too
