### ISSUE TITLE
Getting Price issue on final checkout amount

### ISSUE THREAD

**Issue by sahiliotasol** [moltin/js-sdk#32]
Hi I am getting price issue on Moltin checkout

price is adding to cart api correctly but while calling cart complete api for checkout getting price issue

 ex. if total is $200 then getting $20 on cart complete checkout (edited)

every amount is divided by 10

can you tell me why I am getting this issue???

Here is the code which I am using 

Adding items to cart

moltin.Cart.Insert(cartArrayObj[length-1].obj.id, cartArrayObj[length-1].qty,null,function(obj){
            return countdown(length - 1,cartArrayObj);
          });

Cart checkout

var order = moltin.Cart.Complete({
        gateway: user.role=="-1" && !obj.isTrialOrder ?'paypal-express':'manual',
        customer: {
          first_name: user.name,
          last_name:  user.surname,
          email:      user.email
        },
        bill_to: {
          first_name: user.name,
          last_name:  user.surname,
          address_1:  invoiceData.clientCompanyAddress,
          city:       invoiceData.clientCompanyCity,
          county:     invoiceData.clientCompanyProvince,
          country:    invoiceData.clientCompanyCountry,
          postcode:   invoiceData.clientCompanyPostalCode
        },
        ship_to: 'bill_to',
        shipping: 'free_shipping'
      },function(success){
     });

**Comment by outrunthewolf** [comment]
I think you
