### ISSUE TITLE
Inventory -- zero or infinity?

### ISSUE THREAD

**Issue by tremby** [moltin/js-sdk#344]
I've read the [basics about inventory](https://documentation.elasticpath.com/commerce-cloud/docs/concepts/inventory.html) and I'm trying to check inventory of specific products, so I can adjust my UI based on stock level.

[This other page](https://documentation.elasticpath.com/commerce-cloud/docs/api/catalog/inventory/index.html) then says that if an initial stock level isn't set, the inventory is set to zero. But Elastic Path is still letting me add such a product to the cart, so I guess it's really treating it as infinity if unset.

I'm checking the stock level with [`Moltin.Inventories.Get`](https://documentation.elasticpath.com/commerce-cloud/docs/api/catalog/inventory/get-all-product-stock.html) and it gives some numbers back. In the cases of products where we haven't set a stock level, I'm getting all zeros back.

But how am I to know whether this means "stock hasn't been set", which I'd treat as infinity, or whether it really means zero because it's sold out?

**Comment by samblacklock** [comment]
Hey @tremby 

> But Elastic Path is still letting me add such a product to the cart, so I guess it's really treating it as infinity if unset

Do you have `manage_stock` set to `true` for this product? 

> In the cases of products where we haven't set a stock level, I'm getting all zeros back.
>
> But how am I to know whether this means "stock hasn't been set", which I'd treat as infinity, or whether it really means zero because it's sold out?

A call to `inventories` can return 'all zeros' for both where stock has run out, or as you say when stock level has never been set - but the add to cart action will only respect that inventory level if `manage_stock` is `true`

[Docs link](https://documentation.elasticpath.com/commerce-cloud/docs/api/catalog/products/update-a-product.html)

**Comment by tremby** [comment]
That was the clue I needed: I need to look at the value of `manage_stock`. If it's `true` I query for stock info and pay attention to the result. If it's `false` I don't.

I realize this is an API thing rather than an SDK thing, but wouldn't it make more sense for the inventory query to give a different response if stock isn't being managed for that product?

Some clearer docs regarding this (such as mention of `manage_stock` on any/all of the doc pages I linked above) may be helpful.

Thanks!

**Comment by samblacklock** [comment]
Great to hear that resolved it @tremby. We have raised an internal ticket with the docs team to call this out explicitly, so they should be updated shortly, thanks for bringing this to our attention

> I realize this is an API thing rather than an SDK thing, but wouldn't it make more sense for the inventory query to give a different response if stock isn't being managed for that product?

From a discussion with the team this morning, this is symptomatic of our architecture in that catalogue and inventory services are completely decoupled, but it's a valid point and potentially something we could look to improve upon with future catalogue iterations (cc. @cwmoltin)

I'll close this as resolved but feel free to reach out to [support](https://elasticpath.zendesk.com/hc/en-us) with anything else!
