### ISSUE TITLE
Is this repo maintained? Where are the API docs?

### ISSUE THREAD

**Issue by tnolet** [moltin/js-sdk#38]
Hi,

just evaluating Moltin, but slightly concerned about the lack of docs (I know there are REST api docs, but I mean the JS/NodeJS docs) and the lack of activity. Is this ripe for production?

Not trying to troll.

**Comment by agonbina** [comment]
I was evaluating Moltin but the lack of activity in the main SDK that they are offering is worrying to say the least. A product whose main offering is an SDK, that has unaddressed questions/issues(for a few months now), does not look to be ready for production use at all.

**Comment by AJSturrock** [comment]
Hey @tnolet @agonbina, The JS SDK is being used in production on hundreds of sites. Apologies for the lack of activity, our main offering is the actual API which takes up a lot our focus. Going forward we'll work a bit harder to respond to issues on our SDKs and provide more documentation.

The readme and taking a look at the methods available in the features directory should get you pretty far as they all work the same way but if there is anything in particular that needs improved  just let us know or open a P/R. There are also some JS examples available at http://docs.moltin.com/

**Comment by tnolet** [comment]
@AJSturrock thanks for the reply.
