### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.molt.in api.molt.in:443

### ISSUE THREAD

**Issue by genezablan** [moltin/js-sdk#40]
This is my code

function getCategoryTree(){
  moltin.Authenticate(function() {
    moltin.Category.Tree(null, function(tree) {
        app.locals.catTree = tree;
    }, function(error) {

```
    // Something went wrong...
});
```

  });
}

**Comment by outrunthewolf** [comment]
You might need to give us a bit more information. Please Join the hub and we can help out there.
