### ISSUE TITLE
Promotion code sticks to cart after deleting it

### ISSUE THREAD

**Issue by kareem3d** [moltin/js-sdk#44]
Try to apply a discount code then delete the cart and add item to the new cart you will see that the discount code works on the new cart as well!

This is because you have to run the `Cart.Identifier` after deleting the cart to create a new id for it... which I think you should hardcode it in your script after the `Cart.Delete` promise resolves.

Thanks

**Comment by outrunthewolf** [comment]
We released a patch to remedy this issue.

You should always delete a cart once it is finished with to stop that happening, and generate a new cart ID.
