### ISSUE TITLE
Please publish it to npm

### ISSUE THREAD

**Issue by suhaotian** [moltin/js-sdk#45]
Then I can:
```shell
npm install moltin --save
```
```js
var Moltin = require('moltin')
```

**Comment by andrew-waters** [comment]
Hey @suhaotian - you should be able to install via NPM using the following command:

`npm install moltin --save`

The package is [available here](https://www.npmjs.com/package/moltin).

**Comment by suhaotian** [comment]
Wow! Thank you ! Maybe the documention about JS-SDK should add this to install section !

**Comment by andrew-waters** [comment]
Great, glad it worked for you. It's in the [README](https://github.com/moltin/js-sdk/blob/master/README.md) already, so I'll close this.

**Comment by suhaotian** [comment]
It could work with webpack in browser ?
