### ISSUE TITLE
Nodejs SDK error

### ISSUE THREAD

**Issue by suhaotian** [moltin/js-sdk#47]
My code:
```js
// test.js
const M = require('moltin')

const m = new M({debug: true, publicId: 'xxx', secretKey: 'xxx'})

m.Authenticate(function(){
    console.log('success')  // log
    createTax()
})

function createTax() {
        m.Product.Create({
            title:             'My First Product',
            slug:              'my-first-product-',
            sku:               'my-sku',
            price:             10.00,
            status:            1,
            category:          1396075875539092372,
            stock_level:       1000,
            stock_status:      1,
            tax_band: 1396202847816647595,
            requires_shipping: 0,
            catalog_only:      0,
            description:       'My very first amazing product!'
        }, function(product) {
            console.log('product', product); 
        }, function(error) {
            console.log(error) // log 'error',just a string 'error', not a object
        }); 

}
```

Nothing happen. Just log 'success' and 'error'. Could tell me what's wrong here ?

**Comment by matthew1809** [comment]
Hey Suhaotain,

If you log out the body as the error, you'll see more info on what's going on. It might be an issue with tax band/category.

i.e.

`// test.js
const M = require('moltin')

const m = new M({debug: true, publicId: 'xxx', secretKey: 'xxx'})

m.Authenticate(function(){
    console.log('success')  // log
    createTax()
})

function createTax() {
        m.Product.Create({
            title:             'My First Product',
            slug:              'my-first-product-',
            sku:               'my-sku',
            price:             10.00,
            status:            1,
            category:          1396075875539092372,
            stock_level:       1000,
            stock_status:      1,
            tax_band: 1396202847816647595,
            requires_shipping: 0,
            catalog_only:      0,
            description:       'My very first amazing product!'
        }, function(product) {
            console.log('product', product); 
        }, **function(error, body) {
            console.log(body) 
        }**);

}`

**Comment by suhaotian** [comment]
Thank you ! Could write in doc ?? That's very helpful !!
