### ISSUE TITLE
Create product with image upload

### ISSUE THREAD

**Issue by suhaotian** [moltin/js-sdk#48]
The **images** endpoint need **assign_to** that the ID number of the object to which you want to attach this image. But the problem is when I create product, it's ID automatically populated, So how to attach the upload image to a create product ?

**Comment by outrunthewolf** [comment]
Hi @suhaotian We don't usually allow image uploads in JS.

But you can create the product, and lets say you get ID: 123456 back, then you can use that ID to assign the image to the product on a seperate call.
