### ISSUE TITLE
PCM products/productId/nodes endpoint response

### ISSUE THREAD

**Issue by IgnacioNMiranda** [moltin/js-sdk#555]
Using `{{pcmUrl}}/products/{{productId}}/nodes` obtains a product's nodes but these do not have their parent relationship. Is this behaviour intentional?
Also, it does not exist an SDK function to access to this endpoint, forcing you to use `fetch`, `axios` or another HTTP request library, having to do something like this:

![image](https://user-images.githubusercontent.com/38511917/139773151-5724844e-278d-4cae-8d03-3c2c6225dfe9.png)

Thank you in advance for your feedback!

**Comment by field123** [comment]
resolved by https://github.com/moltin/js-sdk/pull/689
