### ISSUE TITLE
JS-SDK v2 - Wiki: Authentication; wrong attribute.

### ISSUE THREAD

**Issue by nickvonh** [moltin/js-sdk#62]
The wiki shows the payload as
```
const Moltin = moltin.gateway({
  client_id: 'XXX'
});
```
This throws an error of `TypeError: Cannot read property 'length' of undefined`
After looking further into the codebase, it is apparent that the correct payload should be:
```
const Moltin = moltin.gateway({
  publicId: 'XXX'
});
```

**Comment by ynnoj** [comment]
@nickvonh The wiki is up-to-date: `client_id` is the correct key to use when instantiating. However the latest published version of the package is outdated and still uses `publicId`.

We will be publishing an new version that includes this change this week 🙃
