### ISSUE TITLE
Question: Filter by custom fileds

### ISSUE THREAD

**Issue by PodaruDragos** [moltin/js-sdk#629]
Hello is it possible to make a filter for custom fields ? or any kind of mechanism that will do this.

I don't know if this have been asked before, but this is a very common scenario ( and I do believe is something that people asked and might ask again in the future ). 
Maybe provide some sort of example in the Readme

Looking forward to an answer regardless.

**Comment by field123** [comment]
Hi 👋 @PodaruDragos 

We want to try and keep issues on this repository specific to the js-sdk but I can offer a some insight.

Our current support is limited for filtering on custom fields you can see in our docs [here](https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/products/get-all-products.html#filtering-on-custom-data-flows)

Internally we are discussing the possibility of improving this functionality but nothing is on the roadmap as of yet.
