### ISSUE TITLE
Type issue with "hierarchies" / "hierarchy_id" and the GET /catalog response

### ISSUE THREAD

**Issue by scernisevs** [moltin/js-sdk#635]
Type issue with "hierarchies" / "hierarchy_id" and the GET /catalog response

Types coming in from the SDK:
![image](https://user-images.githubusercontent.com/73180534/169498075-3dfc9c12-064c-4632-80d5-477b84dca5a6.png)

  Types coming in from GET https://api.moltin.com/catalog
![image](https://user-images.githubusercontent.com/73180534/169498138-1cf802eb-449c-4c2f-9a54-4b88a760be56.png)

Steps to reproduce:
- GET https://api.moltin.com/catalog (with relevant headers)
- Observe

**Comment by petro97** [comment]
Looks like we don't have a `/catalog` endpoint and types for this in SDK at all. Docs about this endpoint: https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/releases/get-the-catalog.html
Regarding the `CatalogBase` interface its for Get All Catalogs endpoint: https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/configure/get-all-catalogs.html

**Comment by petro97** [comment]
Looks like we don't have a `/catalog` endpoint and types for this in SDK at all. Docs about this endpoint: [Get the Catalog · Commerce Cloud](https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/releases/get-the-catalog.html) 
Regarding the CatalogBase interface it's for Get All Catalogs endpoint: [Get all Catalogs · Commerce Cloud](https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/configure/get-all-catalogs.html)

**Comment by petro97** [comment]
It's fixed. I added Get `/catalog` endpoint. To call this endpoint you should query like:`this.SDK.Catalog.Catalog.Get()`. Response types you can find in the `catalog.d.ts` file, `CatalogReleaseBase` interface.
