### ISSUE TITLE
Can't remove item from current Cart

### ISSUE THREAD

**Issue by nclsmitchell** [moltin/js-sdk#86]
Hello,

When trying to remove an item from my current cart, I get the error:
`Invalid JSON: Unexpected token u in JSON at position 8`

I am using the following code with `import { gateway as MoltinGateway } from 'moltin'
`:
```
removeFromCart(id) {
    const Moltin = MoltinGateway({
        client_id: 'MY_CLIENT_ID'
    })
    Moltin.Cart.RemoveItem(id).then((cart) => {
        this.props.dispatch(updateCart(cart))
    })
}
```

It seems that a payload is send that shouldn't be here:
`{"data":undefined}`

Do you know why this payload is send?

Thank you in advance!

**Comment by ynnoj** [comment]
@nclsmitchell Which version of the library are you using? I believe this should of been fixed in [`2.2.2`](https://github.com/moltin/js-sdk/releases/tag/v2.2.2).

**Comment by nclsmitchell** [comment]
Ok I have the 2.1.0 version but can't install a newer version than 2.2.0 via npm install...

**Comment by ynnoj** [comment]
@nclsmitchell `npm install @moltin/sdk`
