### ISSUE TITLE
Get the main image url for the product?

### ISSUE THREAD

**Issue by anitricks** [moltin/js-sdk#98]
Hi there,

I just started to use the moltin js-sdk and have read almost everywhere but can't find how to get the main-image url for the product? the Files section of the Wiki is missing for something and I don't want to use the REST API for get the link. How should I retrieve the main-image when I do Moltin.Products.All() ?

Any help would appreciated. Thanks

**Comment by ynnoj** [comment]
@anitricks You can use the `With()` method to include related resources with your request.

```js
Moltin.Products.With(['main_image']).All()
.then(response => 
  // Do something
});
```

There'll be an `included` member at the top level of the response which will include the related `file` records from the `main_image` relationship on all your products. You could then find the record in the array using the resource reference from the product relationship.

```js
const mainImage = response.included.main_images.find((main_image) => {
  const relationshipId = product.relationships.main_image.data.id;

  return main_image.id === relationshipId;
});
```

Hope this helps ✌️
