### ISSUE TITLE
'@moltin/sdk' is not in the npm registry.

### ISSUE THREAD

**Issue by danielpiedra** [moltin/js-sdk#99]
i get this when trying to install this package, already tried a couple solutions that google mentioned but only thing working is doing ``"@moltin/sdk": "https://github.com/moltin/js-sdk.git"`` in package.json, not ideal though.

Any thoughts?

**Comment by ynnoj** [comment]
@danielpiedra Sorry you're having trouble. Are you able to share the install command you're using? I've just installed without any issues using `npm install @moltin/sdk`.

**Comment by ynnoj** [comment]
@danielpiedra I just cloned that repo and did a fresh `npm install` with no problems.

What registry is your `npm` client looking at? Have you set a custom one in `.npmrc`?

**Comment by danielpiedra** [comment]
@ynnoj that was it, forgot recently I added `_auth = .... always-auth = true` to the user config, thanks for shining some light on this.

**Comment by ynnoj** [comment]
No problem, let me know if you encounter any issues or have any questions!
